### PR TITLE
handle empty host header

### PR DESCRIPTION
**Pull request by twirkman**
Any reason not to catch errors on web socket requests like we do on http?

### CODE REVIEW

**Comment by shannon** [comment]
Hmm it looks like that whole block must not be correct. I don't think we've ever had a websocket redirect either but both that and the catch will throw since there is no res parameter in a websocket request. But in theory there never should be a websocket redirect since it should have already been handled by the initial request which is a standard http request and ws requests are only on 'upgrade'. So I would make that whole block something like this

```
  function handleWSRequest(req, socket, head){
    //get target and then proxy request
    server.getTarget(req.socket.remoteAddress, req.headers.host, port).then(function(target){
      server.proxy.ws(req, socket, head, {
        target: 'ws://' + target.url,
        xfwd: true
      });
    }).catch(function(error){
      console.log(error);
    });
  }
```

That's strange that you were getting no host header though. Must be some non-browser making requests directly.

**Comment by twirkman** [comment]
Right. Also getting nonsense hosts.

**Comment by shannon** [comment]
What does a nonsense header look like exactly?

**Comment by twirkman** [comment]
something like `testp4.pospr.waw.pl`

**Comment by shannon** [comment]
oh :) yea not technically nonsense but nothing we care about. Judging by the number of unrelated subdomains that come up for waw.pl my guess is it's just some bot or something.

**Comment by twirkman** [comment]
Nonsense meaning not the address the request was routed to

**Pull request merged**
